### ISSUE TITLE
Please set the beta version as the main file in NexusMods

### ISSUE THREAD

**Issue by Eliasyoussef47** [Dakraid/Vortex_Fallout76#2]
The Beta version seems to be working fine. People are complaining this extension isn't working because Vortex is downloading the old not working file (which is the main file). The optional file "Fallout76Support-Beta" should become the main file so that people can get a working version installed by vortex.

**Comment by Dakraid** [comment]
This has been addressed as of the latest uploads.

**Comment by Eliasyoussef47** [comment]
Thank you.
